### ISSUE TITLE
Add support of prettier-plugin-astro

### ISSUE THREAD

**Issue by iamkhan21** [dprint/dprint-plugin-prettier#10]
Please, add [prettier-plugin-astro](https://github.com/withastro/prettier-plugin-astro)

**Comment by dsherret** [comment]
It should be working in the latest release. I didn't test it though 😅

https://github.com/dprint/dprint-plugin-prettier/releases

**Comment by g-plane** [comment]
If you want to format Astro files with dprint, try: https://github.com/g-plane/markup_fmt
