### ISSUE TITLE
Support file extension-specific configuration

### ISSUE THREAD

**Issue by midgleyc** [dprint/dprint-plugin-prettier#17]
Thanks for making this -- it's a lot faster than prettier straight.

Unfortunately I can't port my config over. Prettier supports automatically reading config from a `.editorconfig` file, and I'm using that to use single quotes in `.ts` files and double quotes elsewhere (e.g. SCSS)

```
[*]
quote_type = double

[*.ts]
quote_type = single
```

Could you make it possible to specify prettier config for extensions individually? For example, something like:
```
{
  "prettier": {
    "singleQuote": false,
    "ts.singleQuote": true
  }
}
```
would translate the above (although there might be a better design).

**Comment by dsherret** [comment]
@midgleyc the "overrides" is supported now. Thanks for investigating that! You will need to upgrade to dprint 0.28 and dprint-plugin-prettier 0.8 though

**Comment by midgleyc** [comment]
Hi @dsherret . Thanks for the prompt update, I see that `dprint` is now reading the configuration file.

Unfortunately it is not working for me. I have put together a repository at https://github.com/midgleyc/dprint-prettier-test to show the issue: with the same config across `prettier` and `dprint`, `prettier` picks up the overrides, but it seems `dprint` does not.

**Comment by dsherret** [comment]
Should be fixed now. Added a test and updated the readme: https://github.com/dprint/dprint-plugin-prettier#file-extension-specific-configuration

**Comment by midgleyc** [comment]
Works great now, thank you!
