### ISSUE TITLE
Fails to run on linux

### ISSUE THREAD

**Issue by HymanZHAN** [dprint/dprint-plugin-prettier#2]
### Problem

I installed `dprint` with `cargo`, and configured my project with `dprint init`. I tried to use this Prettier plugin but it fails with the following message:

```shell
> dprint check
[dprint-plugin-prettier]
Catastrophic error sending response. At point of no recovery: Error: EBADF: bad file descriptor, write
Error: EBADF: bad file descriptor, write
[dprint]
Error getting plugin from cache. Forgetting from cache and retrying. Message: There was a problem checking the plugin schema version. This may indicate you are using an old version of the dprint CLI or plugin and should upgrade. failed to fill whole buffer
[dprint-plugin-prettier]
Catastrophic error sending response. At point of no recovery: Error: EBADF: bad file descriptor, write
Error: EBADF: bad file descriptor, write
Error resolving plugin https://plugins.dprint.dev/prettier-0.2.0.exe-plugin: There was a problem checking the plugin schema version. This may indicate you are using an old version of the dprint CLI or plugin and should upgrade. failed to fill whole buffer
```

### Environment
- dprint version: 0.11.1
- config file:

```json
{
  "$schema": "https://dprint.dev/schemas/v0.json",
  "projectType": "educational",
  "incremental": true,
  "typescript": {},
  "json": {},
  "markdown": {},
  "includes": ["**/*.{vue,ts,tsx,js,jsx,json,md}"],
  "excludes": ["**/node_modules", "**/*-lock.json"],
  "plugins": [
    "https://plugins.dprint.dev/typescript-0.40.3.wasm",
    "https://plugins.dprint.dev/json-0.8.0.wasm",
    "https://plugins.dprint.dev/markdown-0.5.1.wasm",
    "https://plugins.dprint.dev/prettier-0.2.0.exe-plugin@5fc84274198107b5464477803eea335ab3c978738ff40058294b105d2e32d5ae"
  ],
  "prettier": {
    "trailingComma": "es5",
    "tabWidth": 2,
    "semi": true,
    "printWidth": 100,
    "bracketSpacing": true,
    "arrowParens": "always"
  }
}
```

**Comment by dsherret** [comment]
@HymanZHAN what operating system are you using?

Luckily this plugin will probably soon be a wasm plugin and should be very portable at that point.

**Comment by HymanZHAN** [comment]
Thanks for the quick response and glad to hear that!
I am using WSL2 but I can also try Windows/Fedora if that's the problem.

**Comment by dsherret** [comment]
@HymanZHAN ok, cool. Thanks! I will test this out on WSL soon to see if I can reproduce (going to sleep now though).

I need to implement https://github.com/dprint/dprint/issues/283 to get some automated tests going for every environment

**Comment by dsherret** [comment]
Just tried it out and I am getting the same error on WSL. I'm looking into it now as it didn't happen before.

**Comment by dsherret** [comment]
@HymanZHAN this is resolved now in the latest release https://github.com/dprint/dprint-plugin-prettier/releases

Was a stupid mistake made during refactoring for linux only. I've opened #3 for the future.

**Comment by HymanZHAN** [comment]
I will try it out. Many thanks!
