### ISSUE TITLE
dprint check - Doesn't format?

### ISSUE THREAD

**Issue by sgnilreutr** [dprint/dprint-plugin-prettier#35]
Hi,
I am possibly not understanding the use case of this plugin correctly but,
When I am using the plugin to format the code base, to write so to speak, it doesn't do that. Am I doing something wrong here?

Running the command `dprint check` will only log the found required changes in the console and than error out - no changes to the code base are made.

I am running:
-    "dprint": "^0.30.3",

This is my `dprint.json`:
`{
  "includes": ["src/**/*.{js,jsx,json,md,tsx,ts}"],
  "excludes": ["/node_modules, /build, /dist, /.git, /public"],
  "prettier": {
    "trailingComma": "es5",
    "tabWidth": 2,
    "semi": false,
    "singleQuote": true
  },
  "plugins": [
    "https://plugins.dprint.dev/prettier-0.10.0.json@ca9a97de84cbb2cd60534eb72c0455f3ca8704743917569ace70499136cf5c9c"
  ]
}
`

**Comment by dsherret** [comment]
Hey @sgnilreutr, try running `dprint fmt` instead. The act of formatting and checking are two separate subcommands unlike prettier. Also, check out `dprint help` for more details.

**Comment by sgnilreutr** [comment]
@dsherret Wow, that was a overlooked by me. Thanks for clearing that up and providing this awesome piece of software.
