### ISSUE TITLE
404 for plugin

### ISSUE THREAD

**Issue by dartess** [dprint/dprint-plugin-prettier#45]
https://plugins.dprint.dev/prettier-0.24.0.json@9a57d0d8e440ad90d07a503166af47e7a6a886abd46767933f9c279f72468596

This plugins.dprint.dev page can’t be foundNo web page was found for the web address: https://plugins.dprint.dev/prettier-0.24.0.json@9a57d0d8e440ad90d07a503166af47e7a6a886abd46767933f9c279f72468596
HTTP ERROR 404

**Comment by dsherret** [comment]
That's expected and just special concise syntax that the dprint cli understands in config files. The dprint cli will make a request here: https://plugins.dprint.dev/prettier-0.24.0.json

Essentially it's:

```
<url>@<hash-to-verify>
```

I should maybe update the plugins.dprint.dev server to just serve those files as-is.
