### ISSUE TITLE
Add mac aarch64 build

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint-plugin-prettier#65]
As title.

**Comment by wincent** [comment]
In case anybody is wondering, like I was, whether `aarch64` and `arm64` are the same thing, [they are](https://apple.stackexchange.com/a/451240) 😁

**Comment by zackbcom** [comment]
I am running into this issue as well.

Unable to use this on arm devcontainer images.

```bash
[dprint-plugin-prettier]
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```
