### ISSUE TITLE
Error on formating

### ISSUE THREAD

**Issue by kattsukii** [dprint/dprint-plugin-prettier#73]
[dprint-plugin-prettier]
Error reading stdout message: failed to fill whole buffer

log
WARNING: Formatting is slow for some file x10

system 

fedora:39
pnpm: 8.14.0
node: 20.10.0

**Comment by dsherret** [comment]
This is https://github.com/dprint/dprint-plugin-prettier/issues/72

I'm planning on looking at it tomorrow
