### ISSUE TITLE
Release new versions?

### ISSUE THREAD

**Issue by apfelbox** [dprint/dprint-plugin-prettier#81]
Hi,

there are now new versions released, as the pipeline always fails: https://github.com/dprint/dprint-plugin-prettier/actions/workflows/ci.yml

Thanks
Jannik

**Comment by dsherret** [comment]
Sorry, I didn't notice. This is fixed now by https://github.com/dprint/dprint-plugin-prettier/pull/82

Caused by GH changing the definition of macos-latest on GH actions.
